apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-demo
spec:
  selector:
    matchLabels:
      app: postgres-demo
  serviceName: "postgres-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres-demo
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "mypassword"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
